import { Table, MenuItem, Order, Reservation } from './types';

export const DEFAULT_TABLES: Table[] = [
  { id: 'tbl-1', name: '1-stol (Oyna oldi)', seatsCount: 4, status: 'occupied', currentOrderValue: 145000 },
  { id: 'tbl-2', name: '2-stol', seatsCount: 2, status: 'free', currentOrderValue: 0 },
  { id: 'tbl-3', name: '3-stol (Katta)', seatsCount: 8, status: 'reserved', currentOrderValue: 0 },
  { id: 'tbl-4', name: '4-stol', seatsCount: 4, status: 'free', currentOrderValue: 0 },
  { id: 'tbl-5', name: 'VIP Xona (Milliycha)', seatsCount: 12, status: 'free', currentOrderValue: 0 },
  { id: 'tbl-6', name: 'Hovli 1-stol', seatsCount: 6, status: 'occupied', currentOrderValue: 285000 },
  { id: 'tbl-7', name: 'Hovli 2-stol', seatsCount: 4, status: 'free', currentOrderValue: 0 },
];

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  {
    id: 'menu-1',
    name: 'Choyxona Palovi (Maxsus)',
    price: 38000,
    category: 'taomlar',
    description: 'Toshkentcha usulda, dumba yog\'i va qo\'y go\'shti bilan tayyorlangan milliy palov.',
    isAvailable: true,
  },
  {
    id: 'menu-2',
    name: 'Tandir Somsa',
    price: 12000,
    category: 'taomlar',
    description: 'Tandirda pishgan go\'shtli va dumba yog\'li issiq somsa.',
    isAvailable: true,
  },
  {
    id: 'menu-3',
    name: 'Asalli Shashlik (Qo\'y go\'shti)',
    price: 25000,
    category: 'taomlar',
    description: 'Mavsumiy ziravorlar bilan marinadlangan va olovda pishirilgan qo\'sh go\'sht.',
    isAvailable: true,
  },
  {
    id: 'menu-4',
    name: 'Mastava',
    price: 28000,
    category: 'taomlar',
    description: 'Qatiq bilan birga tortiladigan to\'yimli suyuq taom.',
    isAvailable: true,
  },
  {
    id: 'menu-5',
    name: 'Ko\'k Choy (Limon va Asal bilan)',
    price: 15000,
    category: 'ichimliklar',
    description: 'Maxsus ko\'k choy, yangi limon bo\'laklari va tabiiy asal.',
    isAvailable: true,
  },
  {
    id: 'menu-6',
    name: 'Kofe Cappuccino',
    price: 22000,
    category: 'ichimliklar',
    description: 'Sifatli arabika qahvasidan tayyorlangan quyuq sutli kofe.',
    isAvailable: true,
  },
  {
    id: 'menu-7',
    name: 'Meva Sharbatlari (Yangi siqilgan)',
    price: 24000,
    category: 'ichimliklar',
    description: 'Yangi apelsin, olma yoki sabzi sharbati.',
    isAvailable: true,
  },
  {
    id: 'menu-8',
    name: 'Asalli Tort (Medovik)',
    price: 20000,
    category: 'shirinliklar',
    description: 'Yumshoq korjlar va asalli qaymoqdan iborat klassik medovik.',
    isAvailable: true,
  },
  {
    id: 'menu-9',
    name: 'Fondan (Shokoladli vulqon)',
    price: 28000,
    category: 'shirinliklar',
    description: 'Yuragida issiq shokolad oqib turuvchi shokoladli premium shirinlik.',
    isAvailable: true,
  },
  {
    id: 'menu-10',
    name: 'Margerita Pitsa',
    price: 65000,
    category: 'fastfood',
    description: 'Mozzarella pishlog\'i va maxsus pomidor sousli klassik pitsa.',
    isAvailable: true,
  },
  {
    id: 'menu-11',
    name: 'Klassik Burger',
    price: 32000,
    category: 'fastfood',
    description: 'Mazzali kotlet, barra sabzavotlar va pishloq qo\'shilgan burger.',
    isAvailable: true,
  },
];

export const DEFAULT_RESERVATIONS: Reservation[] = [
  {
    id: 'res-1',
    customerName: 'Anvar Rahimov',
    customerPhone: '+998 90 990 12 34',
    tableId: 'tbl-3',
    tableName: '3-stol (Katta)',
    date: '2026-06-14',
    time: '19:00',
    guestsCount: 6,
    status: 'confirmed',
    notes: 'Kompaniya tug\'ilgan kuni.',
  },
  {
    id: 'res-2',
    customerName: 'Laylo Sobirova',
    customerPhone: '+998 93 450 11 22',
    tableId: 'tbl-2',
    tableName: '2-stol',
    date: '2026-06-14',
    time: '14:30',
    guestsCount: 2,
    status: 'attended',
    notes: 'Oyna oldidan joy bo\'lsin.',
  }
];

export const DEFAULT_ORDERS: Order[] = [
  {
    id: 'ord-1',
    tableId: 'tbl-1',
    tableName: '1-stol (Oyna oldi)',
    status: 'pending',
    items: [
      { menuItemId: 'menu-1', name: 'Choyxona Palovi (Maxsus)', price: 38000, quantity: 2 },
      { menuItemId: 'menu-2', name: 'Tandir Somsa', price: 12000, quantity: 4 },
      { menuItemId: 'menu-5', name: 'Ko\'k Choy (Limon va Asal)', price: 15000, quantity: 1 },
    ],
    totalAmount: 139000, // 38000*2 + 12000*4 + 15000
    date: '2026-06-14',
    time: '12:15',
    waiterName: 'Sardor',
    notes: 'Ziravori kamroq bo\'lsin'
  },
  {
    id: 'ord-2',
    tableId: 'tbl-6',
    tableName: 'Hovli 1-stol',
    status: 'ready',
    items: [
      { menuItemId: 'menu-3', name: 'Asalli Shashlik (Qo\'y)', price: 25000, quantity: 6 },
      { menuItemId: 'menu-10', name: 'Margerita Pitsa', price: 65000, quantity: 1 },
      { menuItemId: 'menu-7', name: 'Meva Sharbatlari', price: 24000, quantity: 3 },
    ],
    totalAmount: 287000, // 25000*6 + 65000 + 24000*3
    date: '2026-06-14',
    time: '11:45',
    waiterName: 'Malika',
  },
  {
    id: 'ord-3',
    tableId: 'tbl-4',
    tableName: '4-stol',
    status: 'paid',
    items: [
      { menuItemId: 'menu-11', name: 'Klassik Burger', price: 32000, quantity: 2 },
      { menuItemId: 'menu-6', name: 'Kofe Cappuccino', price: 22000, quantity: 2 },
      { menuItemId: 'menu-8', name: 'Asalli Tort (Medovik)', price: 20000, quantity: 2 },
    ],
    totalAmount: 148000,
    date: '2026-06-13',
    time: '18:30',
    waiterName: 'Sardor',
    paymentMethod: 'click'
  },
];

export const TRANSLATIONS = {
  uz: {
    // Nav & General
    dashboard: 'Boshqaruv paneli',
    analytics: 'Moliya & Tahlil',
    reports: 'Hisobotlar',
    orders: 'Buyurtmalar',
    menu: 'Raqamli Menyu',
    reservations: 'Bronlar kitobi',
    settings: 'Sozlamalar',
    search: 'Qidiruv',
    searchShortcut: 'qidirish...',
    searchPlaceholder: 'Qidiruv (stollar, buyurtmalar, taomlar)...',
    welcomeBack: 'Xush kelibsiz',
    activeTables: 'Band stollar',
    freeTables: 'Bo\'sh stollar',
    totalTables: 'Jami stollar',
    createTable: 'Stol qo\'shish',
    createTablePlaceholder: 'Masalan: VIP xona, Hovli 5...',
    noFolders: 'Stollar mavjud emas',
    upgradeTitle: 'Premium Tarifga O\'ting!',
    upgradeDesc: 'Cheksiz buyurtmalar boshqaruvi va kafe logotipini sozlashingiz mumkin.',
    upgradeButton: 'Hozir yangilash',
    upgradeSuccess: 'Muvaffaqiyatli! Premium imkoniyatlar faollashtirildi.',
    totalOrders: 'Jami buyurtmalar',
    dailyRevenue: 'Kunlik tushum',
    averageBill: 'O\'rtacha chek',
    activeOrders: 'Faol jarayonlar',
    recentOrders: 'Oxirgi buyurtmalar',
    seeAll: 'Barchasi',
    view: 'Ko\'rish',
    sign: 'To\'lash',
    delete: 'O\'chirish',
    signThisContract: 'Buyurtmani yakunlash / To\'lov',
    contractValue: 'Umumiy summa',
    category: 'Kategoriya',
    status: 'Holat',
    date: 'Sana',
    time: 'Vaqt',
    client: 'Mijoz / Stol',
    signedBy: 'Yakunlagan xodim',
    onDate: 'sanasida',
    contractCreated: 'Buyurtma muvaffaqiyatli ochildi!',
    contractDeleted: 'Buyurtma bekor qilindi.',
    notSignedYet: 'To\'lanmagan (Faol)',
    searchNoResults: 'Mos keladigan buyurtma yoki taom topilmadi.',
    typeYourSignature: 'Mehmon sharhi (Ixtiyoriy)',
    signaturePlaceholder: 'Masalan: Xizmat ko\'rsatish alo darajada bo\'ldi',
    clear: 'Toza',
    confirmSigning: 'To\'lovni Tasdiqlash',
    viewDocument: 'Chekni Ko\'rish',
    createContract: 'Yangi buyurtma ochish',
    contractTitleLabel: 'Zaxira eslatmasi',
    clientNameLabel: 'Ofitsiant ismi',
    clientEmailLabel: 'Ofitsiant kodi / E-pochta',
    valueLabel: 'Boshlang\'ich buyurtma miqdori',
    selectTemplate: 'Menu taomlarini tanlang',
    selectFolderCategory: 'Stolni belgilang',
    cancel: 'Bekor qilish',
    save: 'Yuborish',
    customContract: 'Qo\'shimcha ko\'rsatmalar',
    draft: 'Qoralama',
    pending: 'Tayyorlanmoqda',
    ready: 'Tayyor',
    served: 'Tortilgan',
    paid: 'To\'langan',
    cancelled: 'Bekor qilingan',
    currencyType: 'Valyuta',

    // Menu Translate
    taomlar: 'Asosiy taomlar',
    ichimliklar: 'Salqin va issiq ichimliklar',
    shirinliklar: 'Desertlar / Shirinliklar',
    fastfood: 'Fastfud / Pitsa',
    newMenuItem: 'Yangi taom qo\'shish',
    dishName: 'Taom nomi',
    dishPrice: 'Narxi',
    dishCategory: 'Kategoriya',
    dishDescription: 'Tarkibi / Tavsifi',
    available: 'Sotuvda bor',
    unavailable: 'Tugagan',
    menuExplanation: 'Mijozlarga taklif qilinadigan faol taomnomani boshqaring va narxlarini belgilang.',

    // Tables
    allTables: 'Barcha stollar va xonalar',
    addTable: 'Yangi stol',
    tableCapacity: 'Sig\'imi (kishilik)',
    tableStatus: 'Stol holati',
    free: 'Bo\'sh va tayyor',
    occupied: 'Band (Mijoz bor)',
    reserved: 'Bron qilingan',

    // Reservations
    newReservation: 'Stol band qilish',
    guestName: 'Mehmon ismi',
    guestPhone: 'Telefon raqami',
    guestCount: 'Kishilar soni',
    reservationTime: 'Kelish vaqti',
    reservationNotes: 'Alohida istaklar',
    attended: 'Keldi',
    confirmed: 'Tasdiqlangan',

    // Themes / Workspace
    workspaceSettings: 'Muassasa sozlamalari',
    personalProfile: 'Boshqaruvchi profili',
    fullName: 'Boshqaruvchi ismi',
    companyName: 'Kafe / Restoran nomi',
    currencyUnit: 'Amaldagi valyuta',
    saveSettings: 'Sozlamalarni saqlash',
    settingsSaved: 'Sozlamalar saqlandi!',

    // Analytics Spec
    revenueTrend: 'Haftalik/Oylik tushum grafigi',
    categoryChart: 'Kategoriyalar bo\'yicha sotuv ulushi',
    statusChart: 'Buyurtmalar bajarilishi tahlili',
    growthRate: 'Haftalik o\'sish sur\'ati',
    exportReport: 'Excel formatida yuklash',
    generating: 'Hisobot shakllanmoqda...',

    // Upgrage Modal Spec
    membershipInfo: 'Lunor Premium Kafe',
    membershipLimitText: 'Bepul versiyada siz faqat 7 ta stol va cheklangan buyurtmalarni boshqara olasiz. Barcha cheklovlarni olib tashlash uchun premium tarifiga o\'ting!',
    unlimitedContracts: 'Cheksiz buyurtmalar tahlili va kassa',
    brandingTheme: 'Brend logotipi va chekdagi shaxsiy yozuvlar',
    analyticsAdvanced: 'Qayta aloqa tizimi va ofitsiantlar reytingi',
    priceText: '89,000 UZS / oy',
    premiumCardNumber: 'Humo / Uzcard raqami',
    premiumCardExpiry: 'Amal qilish muddati (AA/YY)',
    premiumPayButton: 'Faollashtirishni tasdiqlash',
    demandsConfirmed: 'Premium tizim muvaffaqiyatli faollashtirildi!',
  },
  en: {
    // Nav & General
    dashboard: 'Eatery Dashboard',
    analytics: 'Finance & Analytics',
    reports: 'Reports',
    orders: 'Orders Ledger',
    menu: 'Digital Menu',
    reservations: 'Reservations Book',
    settings: 'Cafe Settings',
    search: 'Search Desk',
    searchShortcut: 'search items...',
    searchPlaceholder: 'Search (tables, orders, dishes)...',
    welcomeBack: 'Welcome',
    activeTables: 'Busy Tables',
    freeTables: 'Free Tables',
    totalTables: 'Total Tables',
    createTable: 'Add Table',
    createTablePlaceholder: 'E.g., Terrace 1, VIP Booth...',
    noFolders: 'No tables registered',
    upgradeTitle: 'Upgrade to Business!',
    upgradeDesc: 'Unlock unlimited tables flow, custom printable bills, and waiters metrics.',
    upgradeButton: 'Upgrade to PRO',
    upgradeSuccess: 'Successful! Pro business features activated.',
    totalOrders: 'Total Orders',
    dailyRevenue: 'Daily Revenue',
    averageBill: 'Average check',
    activeOrders: 'Active Processes',
    recentOrders: 'Recent Orders',
    seeAll: 'All',
    view: 'View',
    sign: 'Pay Check',
    delete: 'Cancel',
    signThisContract: 'Settle Bill / Process Payment',
    contractValue: 'Bill Total',
    category: 'Category',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    client: 'Guest / Table',
    signedBy: 'Handled by',
    onDate: 'on date',
    contractCreated: 'New order opened successfully!',
    contractDeleted: 'Order has been cancelled.',
    notSignedYet: 'Unpaid (Active)',
    searchNoResults: 'No matches found in your ledger.',
    typeYourSignature: 'Customer Feedback (Optional)',
    signaturePlaceholder: 'E.g., Exquisite food, super quick!',
    clear: 'Clear',
    confirmSigning: 'Confirm Payment Settlement',
    viewDocument: 'View Receipt',
    createContract: 'Open New Order',
    contractTitleLabel: 'Table / Note label',
    clientNameLabel: 'Waiter Name',
    clientEmailLabel: 'Waiter Code / Email',
    valueLabel: 'Opening Deposit Amount',
    selectTemplate: 'Select Dishes & Beverages',
    selectFolderCategory: 'Select Dining Table',
    cancel: 'Cancel',
    save: 'Send to Kitchen',
    customContract: 'Kitchen Special Notes',
    draft: 'Draft',
    pending: 'Preparing',
    ready: 'Ready',
    served: 'Served',
    paid: 'Settle Paid',
    cancelled: 'Cancelled',
    currencyType: 'Currency',

    // Menu Translate
    taomlar: 'Main Dishes',
    ichimliklar: 'Beverages & Coffee',
    shirinliklar: 'Desserts & Sweets',
    fastfood: 'Fastfood / Pizza',
    newMenuItem: 'Add Menu Item',
    dishName: 'Dish Name',
    dishPrice: 'Price',
    dishCategory: 'Category',
    dishDescription: 'Ingredients / Description',
    available: 'In Stock',
    unavailable: 'Out of Stock',
    menuExplanation: 'Configure your current menu card, set prices, and toggle kitchen availability.',

    // Tables
    allTables: 'Tables & Dining Spaces',
    addTable: 'Add Table',
    tableCapacity: 'Capacity (Guests)',
    tableStatus: 'Table Status',
    free: 'Available / Free',
    occupied: 'Occupied',
    reserved: 'Reserved Booked',

    // Reservations
    newReservation: 'Reserve Table',
    guestName: 'Guest Name',
    guestPhone: 'Phone Number',
    guestCount: 'Guests Count',
    reservationTime: 'Arrival Time',
    reservationNotes: 'Host Preferences',
    attended: 'Arrived',
    confirmed: 'Confirmed',

    // Themes / Workspace
    workspaceSettings: 'Eatery Parameters',
    personalProfile: 'Manager Profile',
    fullName: 'Manager Name',
    companyName: 'Cafe / Restaurant Name',
    currencyUnit: 'Base Currency',
    saveSettings: 'Save Parameters',
    settingsSaved: 'Parameters updated successfully!',

    // Analytics Spec
    revenueTrend: 'Financial Inflow Chart',
    categoryChart: 'Revenue Shares by Category',
    statusChart: 'Order Fulfillment Ratios',
    growthRate: 'Weekly Performance Growth',
    exportReport: 'Download Spreadsheet',
    generating: 'Compiling financial sheet...',

    // Upgrage Modal Spec
    membershipInfo: 'Lunor Premium Cafe',
    membershipLimitText: 'On the free tier, you can manage up to 7 tables and limited daily order logs. Unlock unlimited POS registers.',
    unlimitedContracts: 'Unlimited register tables & automated receipts',
    brandingTheme: 'Custom company typography & printable invoice notes',
    analyticsAdvanced: 'Advanced tables analytics, feedback collection & waiter leaderboard',
    priceText: '$9 / month',
    premiumCardNumber: 'Card Number (Uzcard, Humo, Visa)',
    premiumCardExpiry: 'Expiration Date (MM/YY)',
    premiumPayButton: 'Confirm and Settle License',
    demandsConfirmed: 'Enterprise Cafe License fully unlocked!',
  }
};
